xsuite/xobjects

setup.py, xobjects/context.py, xobjects/typeutils.py
**New features:**
- When passing ```_offset=packed``` upon creation of a new xobject the default memory alignment is ignored
- Changed default of ```Buffer.allocate(...)``` to ```align=True```
Two bug fixes in alignment logics.
=> Introduce offset='packed' option

tests/test_capi.py, tests/test_ref.py, xobjects/capi.py, xobjects/struct.py
Supersedes #61
Closes xsuite/xsuite#178
- add a missing semicolon in `capi.Index_get_c_offset`
- correct the calculation of the right offset (do not discard the value)
- change the return in `capi.gen_c_pointed` so that it does not try to dereference the value of the string
- fix a bug in `Index_get_c_offset` where a type appeared in the wrong place causing compilation issues for dyn-sized arrays
- fix wrong calculation of index offsets in `gen_method_len` for dyn-sized arrays
- fix wrong calculation of index offsets in `Index_get_c_offset` which is needed for `_get` and `_set` kernels
- fix an issue in `struct` where an object with a reference was binary-copied thereby corrupting the reference
=> fix bugs in capi

tests/test_typeutils.py, xobjects/typeutils.py
- To align with the newly updated guide, this throws an error when the explicitly passed buffer is not on the explicitly passed context.
- Following the discussion with @rdemaria, I prohibit passing anything different to `None`, `'packed'`, or `'aligned'` as `offset`. This gets rid of the strange behaviour where:
```python
buffer = xo.get_a_buffer(size=BIGGER, buffer=xo.context_default.new_buffer(SMALLER), offset=OFFSET)
buffer.capacity  # => SMALLER if OFFSET is an integer, otherwise BIGGER
```
- Added a bunch of tests asserting the described behaviour of `get_a_buffer`
CPU tests pass https://github.com/szymonlopaciuk/xsuite/actions/runs/3136410559
=> get_a_buffer: forbid specifying a mismatched buffer+context, offset cannot be a number

xobjects/context_pyopencl.py
This updates the calls to `cl.enqueue_copy` in `context_pyopencl` to get rid of deprecation warnings.
Fixes xsuite/xsuite#150.
Mandatory: 
Optional:
=> update the calls to cl.enqueue_copy to new api

tests/test_array.py, xobjects/array.py
Before `a.x=value` where `x` is an `xo.Array` would write data of any length starting from the offset of `x` regardless of the size allocated.
Mandatory: 
Optional:
=> add _update method to class to avoid overwriting arrays

xobjects/context_pyopencl.py
While some vendors define NULL, OpenCL C 1.2 does not do so by itself. This PR adds an explicit definition to prevent the following compilation error when trying to run the [simple example](https://xsuite.readthedocs.io/en/latest/singlepart.html#a-simple-example) with OpenCL context on an AMD GPU:
```
Traceback (most recent call last):
File "/xsuite/example.py", line 32, in <module>
tracker = xt.Tracker(_context=context, line=line)
File "/usr/local/lib/python3.10/dist-packages/xtrack/tracker.py", line 92, in __init__
self._init_track_no_collective(
File "/usr/local/lib/python3.10/dist-packages/xtrack/tracker.py", line 350, in _init_track_no_collective
self._build_kernel(save_source_as, compile=compile)
File "/usr/local/lib/python3.10/dist-packages/xtrack/tracker.py", line 713, in …
```
=> [OpenCL] Ensure NULL definition

xobjects/hybrid_class.py
Fix error `object has no attribute '_fields'` for new elements with an empty `_xofields` dict.
Required for https://github.com/xsuite/xtrack/pull/252
=> Fix indentation

tests/test_kernel.py, xobjects/context.py, xobjects/context_cpu.py, xobjects/context_cupy.py, xobjects/context_pyopencl.py
Add functionality to save built CFFI kernels, and to build them without necessarily adding them to the current context.
Part of the solution for xsuite/xsuite#224.
Mandatory: 
Optional:
=> Allow for saving built CFFI kernels

xobjects/context_cpu.py
Inside ContextCpu.add_kernels(): save_source_as is not passed to build_kernels()
Closes # .
Mandatory: 
Optional:
=> Add missing save_source_as parameter

tests/notest_capi.py, tests/test_capi.py, tests/test_struct.py, xobjects/_patch_pyopencl_array.py, xobjects/context.py, xobjects/context_cpu.py, xobjects/context_cupy.py, xobjects/context_pyopencl.py, xobjects/hybrid_class.py, xobjects/linkedarray.py, xobjects/ref.py, xobjects/specialize_source.py, xobjects/struct.py
This patches `pyopencl` with a couple of functions that are available on `numpy` already: `sqrt` and `isnan`.
Needed by https://github.com/xsuite/xpart/pull/61 to abstract some logic.
Mandatory: 
Optional:
=> Patch pyopencl with sqrt and isnan functions

tests/test_kernel.py, xobjects/context.py, xobjects/context_cpu.py, xobjects/context_cupy.py, xobjects/context_pyopencl.py, xobjects/hybrid_class.py, xobjects/struct.py
This introduces a mechanism that can allow to override HybridClasses by:
- letting the user change the name of the underlying XoStruct
- taking the "newer" XoStruct in sort_classes if two are provided
This is useful for defining multiple implementations of Particles class. The base specifies the interface xobject that all Particles need to conform to. These can then be overriden to add more fields or custom C methods.
Replaces #93.
Needed for xsuite/xpart#73.
Mandatory: 
Optional:
=> Allow for "overriding" HybridClasses (without "minitracker")

xobjects/context.py, xobjects/context_cpu.py, xobjects/context_cupy.py, xobjects/context_pyopencl.py
Don't use generic type hints, which are not supported in Python 3.6. Fix some that were not correct.
Closes xsuite/xsuite#319.
Mandatory: 
Optional:
=> Correct type annotations, use typing supported in Python 3.7

tests/test_struct.py, xobjects/__init__.py, xobjects/context_cpu.py, xobjects/general.py, xobjects/struct.py
Fixes a bug where the flag `only_if_needed` in `HybridClass.compile_class_kernels` was essentially ignored, as the code of the method was not adapted to the recent changes in #96; added a test to for tracking this regression.
Closes xsuite/xsuite#320
Mandatory: 
Optional:
=> bugfix: unnecessary recompilations in `HybridClass.compile_class_kernels`

xobjects/context.py, xobjects/context_cpu.py, xobjects/test_helpers.py
This PR is part of the effort to enable OpenMP support in Xsuite. An xobjects context supporting OpenMP can be spawned with `ContextCPU(omp_num_threads=N)`, where `N` is a positive integer specyfing the number of threads to spawn, or a string `"auto"`, which will let OpenMP choose the most optimal number.
Closes xsuite/xsuite#15.
Mandatory: 
Optional:
=> Add support for OpenMP

xobjects/context_cpu.py, xobjects/context_cupy.py, xobjects/context_pyopencl.py
Add link to a scipy-like lib in context CPU and Cupy following the implementation of the numpy-like lib
Closes # .
Mandatory: 
Optional:
=> Add link to a scipy-like lib in context CPU and Cupy

setup.py
Add a missing test dependency on `pytest-mock` to `setup.py`.
Mandatory: 
Optional:
=> add a missing dependency on pytest-mock to setup.py

xobjects/context.py, xobjects/context_cpu.py, xobjects/hybrid_class.py, xobjects/struct.py
When compiling kernels at the level of the `xo.Struct`, it will first verify if prebuilt kernels are available that already provide these kernel functions. Until now this functionality only existed for `track_line` but with this PR it also works when tracking individual elements or using individual kernels. For this to work, PR https://github.com/xsuite/xtrack/pull/448 and https://github.com/xsuite/xpart/pull/104 are needed, which provide the necessary changes.
Mandatory: 
Optional:
=> Implemented a way to use prebuilt kernels at the level of the xo.Struct

xobjects/__init__.py, xobjects/general.py, xobjects/test_helpers.py
The module `xobjects.test_helpers` has so far only been used in testing, however currently the function `assert_allclose` is imported from in in `__init__.py` making it part of the main package. The `test_helpers` module requires `pytest`, which we don't necessarily want to be a required dependency, but the current implementation effectively makes it so. This PR moves the `assert_allclose` function to `xobjects.general` instead to avoid this problem.
=> Move assert_allclose to general to avoid a hard dependency on pytest

xobjects/capi.py
Quick fix: when the return value of a `Method` is None, it used to still `return 0;` as a default case (which crashes the compilation).
Mandatory: 
Optional:
=> Fix when return value of Method is None

tests/test_struct.py, xobjects/context_cpu.py
Fixed a small bug in `cdefs` before compiling a CPU kernel.
The code would check if a cdef for this kernel already exists, however, it would do so by checking by the Python name instead of the name in C.
Furthermore, I added a space before and a `(` after the cname to be searched for, as otherwise if kernels exist which have the name of the new kernel as a part, the new one would not be generated.
E.g. if there already is a kernel definition `void LocalSegment_crossing_drift(double s);` then the new kernel `void crossing_drift(double s1, double s2);` would never be generated. Searching for `f" {cname}("` avoids this problem.
All `xobjects` tests pass, and all `xtrack` tests with `ContextCpu` as well (did not test the other contexts as they are not affected).
Mandatory: 
Optional:
=> Bugfix in c defs

xobjects/test_helpers.py
Automatically add a tag (`context_dependent`) to all the tests using `@for_all_test_contexts` and `@require_context`. This allows to select or exclude them using the tag in pytests, e.g. `pytest -m context_dependent` or `-m 'not context_dependent'`.
Mandatory: 
Optional:
=> Mark all @for_all_test_contexts tests with tag `context_dependent`

xobjects/context.py, xobjects/context_cpu.py, xobjects/context_cupy.py, xobjects/context_pyopencl.py, xobjects/hybrid_class.py, xobjects/struct.py
In preparation for using headers when building C tracking code:
- introduce context based defined flags: `XO_CONTEXT_CPU`, `XO_CONTEXT_CPU_SERIAL`, `XO_CONTEXT_CPU_OPENMP`, `XO_CONTEXT_CUDA`, `XO_CONTEXT_CL`.
- add `extra_compile_args` parameter to `Context.add_kernels` and propagate it correctly
Mandatory: 
Optional:
=> Add context-based define flags and propagate extra compile flags
